// <auto-generated />
using System;
using CompanyEmployees.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompanyEmployees.Infrastructure.Migrations
{
    [DbContext(typeof(CompanyEmployeeDbContext))]
    partial class CompanyEmployeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompanyEmployees.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CompanyId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3b1f6e2-5c4a-4d2a-9f3e-1c2d3e4f5a6b"),
                            Address = "123 Innovation Drive",
                            Country = "USA",
                            Name = "Tech Solutions"
                        },
                        new
                        {
                            Id = new Guid("c4d2e3f4-6a7b-8c9d-0e1f-2a3b4c5d6e7f"),
                            Address = "456 Enterprise Ave",
                            Country = "UK",
                            Name = "Global Enterprises"
                        },
                        new
                        {
                            Id = new Guid("d5e6f7a8-9b0c-1d2e-3f4a-5b6c7d8e9f0a"),
                            Address = "789 Tech Park",
                            Country = "Canada",
                            Name = "Innovatech"
                        });
                });

            modelBuilder.Entity("CompanyEmployees.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("EmployeeId");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1e2f3a4-b5c6-7d8e-9f0a-1b2c3d4e5f6a"),
                            Age = 30,
                            CompanyId = new Guid("b3b1f6e2-5c4a-4d2a-9f3e-1c2d3e4f5a6b"),
                            Name = "John Doe",
                            Position = "Software Developer"
                        },
                        new
                        {
                            Id = new Guid("e2f3a4b5-c6d7-e8f9-0a1b-2c3d4e5f6a7b"),
                            Age = 28,
                            CompanyId = new Guid("c4d2e3f4-6a7b-8c9d-0e1f-2a3b4c5d6e7f"),
                            Name = "Jane Smith",
                            Position = "Project Manager"
                        },
                        new
                        {
                            Id = new Guid("f3a4b5c6-d7e8-f9a0-1b2c-3d4e5f6a7b8c"),
                            Age = 35,
                            CompanyId = new Guid("b3b1f6e2-5c4a-4d2a-9f3e-1c2d3e4f5a6b"),
                            Name = "Alice Johnson",
                            Position = "UX Designer"
                        },
                        new
                        {
                            Id = new Guid("a4b5c6d7-e8f9-a0b1-2c3d-4e5f6a7b8c9d"),
                            Age = 40,
                            CompanyId = new Guid("c4d2e3f4-6a7b-8c9d-0e1f-2a3b4c5d6e7f"),
                            Name = "Bob Brown",
                            Position = "Data Analyst"
                        });
                });

            modelBuilder.Entity("CompanyEmployees.Domain.Entities.Employee", b =>
                {
                    b.HasOne("CompanyEmployees.Domain.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CompanyEmployees.Domain.Entities.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
